#!/bin/sh
set -e
echo "*******************************"
echo   "Running git pre-commit hook"
echo "*******************************"

# Run Spotless
#./gradlew spotlessApply
#./gradlew spotlessKotlinApply
