name: Upload build on release tag

on:
    workflow_dispatch: 
      inputs: 
        tag:
          description: 'Enter Tag'
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
    
      - name: Setting up project
        uses: ./.github/actions/setup

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Build Free Release AAB
        id: buildRelease
        run: ./gradlew assembleRelease

      - name: Sign Free AAB
        id: signFree
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/free/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_WITH_PRO }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Sign Pro AAB
        id: signPro
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/pro/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_WITH_PRO }}
          alias: pro
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload free binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.signFree.outputs.signedReleaseFile}}
          tag: ${{ inputs.tag }}
          overwrite: true
          file_glob: true
                - name: Upload binaries to release

      - name: Upload pro binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.signPro.outputs.signedReleaseFile}}
          tag: ${{ inputs.tag }}
          overwrite: true
          file_glob: true
